language: php

php:
    - '7.3'

install:
    - composer install

script:
    - vendor/bin/sculpin --env=prod generate

# Will deploy pushes to master branch on the S3 bucket
deploy:
  - provider: s3
    # New Bucket
    access_key_id:
        secure: "MoI9LCXPDza70hQt//D/mB6ehy1VUbytkQQ8gYQmIANhPyHBK7Nr5cEOAAFoV6X8xMNGNTxRMyycF4AHxwsbjnSwpqBaUBIJvu/j7EDY1qvWAHg3hVNALXDP3CoSpsTzrKUXL8cLtCHQmHjNi1xzY6m53C5ZENq0mgQ2oHwlh2J3Ewf4sgdeadaAyQGo07036BruiE4u0pcj4XT33Fp6B9E9HR37dmsrHI8JNpAe78wt6W2S3yAOg19OmeHl7JiQdzgDPA66OI/9bcea2bC4VpkH94bKMoN7VMYNWWGNmASmBBAi1LNqWI8g6KBrDiTHNsh2yAiabkl9VOlkQQHRKQqeS3Z5MZnFjSov0B2HPGm/3jBvfrHqBiJXnHvcl8Aq7fN12wR4ou0XaKj9okjp0vfu2rpO4uvFcAP0/Rk6Qf9B2LZR5XzmGr7NU7yAMJe7+FvyOYBNECJgKi+qrxWYTs+FIZ9NFm808GqgghBT0fwAt5hTKU3X4nXGG50Ek0gZoLnM77LdLekt53N6mBZ5pNnGfDY4TTOmdUX2xgCtky2dco/9BY3cE4YBDnvaYjAnOB2Ga6Hrwtx0QqMyq1kee7VXGMGAXMc/nnIouXP3w0lkf4iAY9tCNX1Yvwop8ON2zzQD8Q2Ba0gS7rb8ggqLfJo4V/W80ievtvDUYSg/IXs="
    secret_access_key:
        secure: "JnpelQkmT6WO3DR1BpWATQybxdpBt+FzsisNZzIUFB9Vh7MaVV6cGm0GGHuV/TkA1zkSVwWJ3NUtw5AUFvFdszqCGh+nliK4pk52PrRnobARYPvjiIXyqBbzE5Oe5QInSn3TBw0njz6PQegVuOX2TpLWEOrPu2+C5pH4dO8PfTHfpMNPdhiGwUjOW76ZNr89q/ZSydbshRvAF5+2BSUfAWg5wofXEbMmgCiFdJDLeW0roBeBT3wefz19mdzYmzFpHA+rWdonodjDu3uZe7+iyJUMJUnzX9BAF87qdWHlxbQHaHi0OmsVxIOpOgqSLPsvKLd5eM1ZcVISwPqRY3rqJT1Jbi5xGMejHlQc2iU3WdztQKnpXSr3cbHr6KE9lWEbdDYehF7ZVtleYkY2lGDQdjR/V3YZ+T+Nfm4E4V1jPnINmOHmAxQipsJ1V8GBeSW/IWkPIyKeWcNEyJohHKXyTnoGvWoeSVRRoOWLxlmW2KR6+tj7o0/StpVoInh3uDhRBNt8TEuCgAzsdWXITmKkQbw5rprhuHWXPjxkwdulneSR077sF8rFnRyWXCUUYkDqYWeiEEXBm5VQMY45CHR165O04oCY967GrMgj7HfZhB8952sJh51mynyPwbu97w4vX1aIWw5L4YZ7s9wLG9/PlOCq8sSA69xOm3WbxsgQ47w="
    bucket:
        secure: "icC44cg/dV9cByexKTT2nH4sMBebSIdkxxL3eUjeEJtqtU9MSq3QuEqnVmUVltCLV02zmsIQm+CReFw7WgBRZRQ8BjmJ+HedU5cYreHlbOehdoSbDC5Vxphyt2ugyd+VNPZslc7sZrlzcyoKlTBdJ1WyrnrMbAKyXOoy12iBClAPVwFgoEgZ9Whgexvid0wXJ/HIDwDqWyhYtKyHQ5nDz8OWHwMuQRuly2eds0h7uAmbc24qZHFh8VIljn4tp8yGK/yAW1Us6cei+BZkxZQbosOEfbA9YTj3uKWLWoawWwQXhw2BWrFMptjXmRUmzKEwh1nIMlGpIwo+Z7cj/pV8jLO+snh9ihJjCdtWj0g3eitjY/C3JJnUw+Phw3Ip6s5K/3+SqrYMZUPPSnzjDm008gyNJ9sueDHuiaSFXTN9i7uIhC90HXgWnhlHI/S5uJJ8iW4PJYN018AqTT2zUltEHFIk3qTtFfUrZPpeG1StPzwJZ+gW5lPPEnhtd41+Vlo7/Jqvq6h2Iky4PHp5RSXBDUUJL0g/5GvyfuW+n/F6ohF56mp/t+XrTaFC2oUybzL24ibLDVPk2YhYSTetBTmKfct+YiWtQ1uE5v3tX+wme9vtvJNwzt6psd2EDUDY4pQeHEXUlYeUdr9JgBH4Xt76wR2QBBUuBCsMspPJwGa5Q/I="
    region: "us-east-1"
    skip_cleanup: true
    local_dir: output_prod
    on:
        branch: master

notifications:
    slack:
        secure: "gcBFenoUPcbM4npL9kC37aQV2drcUs+Jrg8OvPFebqXTZpaPIkoomJOqfyFjgJmWwF945BXQKFkwovNY3lM4Tja8JqFNoePcAcAPwshSqNS5XJcN7Fxaucpp7hV2mi+Kxpvy1m+cmvUtOhIWqYtJ/v8NqBwpckLJ5QZR6i6rkjpswscW//U3/A5kDyhVfxqVNn+GskX9ZlSpKzqkdE0r5aVmOLcYlBvF6gdlaKsKeiaYvFsp0vtsERNOhs9mfCGIRuZLa8eXOi6QQRZA2/6mI5DkgnUt63y90t1NEMJYpfC0lUV6XeV4LkN6/jCmnFvAtIF+lUL7Q2gAAu8Yt1j/US5X5sd5KJrovvB6Fjrlo60u2hYoeyghrJXewyfysvJJ5zhY1bFmAV8ovFZBxf6CI5DT9cMQEkJQn6sGsHqim1cBmV7naB3rXBcYdSiR4Kbz5iK3LBTzDB8lkPBIMIdvJzDs+D7XNUfZXiorNDPJSBP4V1YKuUwwWQeEw/Pr7uvKjoy2Fn37lMkfBUpacXGsVE+FNHfNTW9svx8rV2+KZFTOWsGaEP3b+znErMDRMuiQk5etG3q/diLvfejGermFzJVrn1cnr/a4D9kMxlZKldUT/eUZKEOTWNxmJZ5H24pd+1RV8GlewKSoVXQ9mdYlbezRoRBRLF6RQ68L6PpnVnE="
