# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: GameStrafe Portal
subtitle: The opensource game network
github_link: https://github.com/gamestrafe/gamestrafe.com

#google_analytics_tracking_id: 1

# Insert your disqus shortname
#disqus:
#    shortname: